# Site settings
title: Larry Chiem
email: larrypchiem@gmail.com
description: Engineer // Intern // Student

# Change the site default images and content here
bg-img: moto.jpg
logo: logo.svg
avatar: face.jpg
about-section: <p>Larry is a full-time computer science student at Portland State University. After his first year of theory classes, he came to realize that those
  courses can only take him so far. He was far more interested in creating
  content and allowing his imagination to roam free. So he took learning
  into his own hands by making apps(<a href="https://developer.android.com/index.html" target="_blank">Android</a> and <a href="https://developer.apple.com/" target="_blank">IOS</a>) and developing websites
  after he would finish his homework. </p>
  <p>He learned to use github via the terminal commands</p>
  <p><b>git status, git add -A, git commit -m "message", git push origin master </p>

# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
