# Site settings
title: Larry Chiem
email: larrypchiem@gmail.com
description: Engineer // Intern // Student

# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested