#-------------------------------
# General Site Settings

title: Larry Chiem
description: Engineer // Intern // Student
email: larrypchiem@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  <b>Larry is a full-time computer science student at Portland State University.</b>
  Most of the things he makes are [cool programs](https://github.com/Chiemychanga){:target="_blank"}.

  <p><b>OOP</b> is a programming language model organized around objects rather than "actions" and data rather than logic.
  <li>Single inheritance</li>
  <li>Encapsulation</li>
  <li>Abstraction</li>
  <li>Polymorphism</li>

  <p>"Ask and you shall receive."
  <p>Strengths: Technical background, Problem-solver, Self-driven
  <p>Weaknesses: Need to work on my management skills, unfamiliar with the latest languages, being too critical of myself

  <p>3 Difficult situations:

  <p>I want to be a part of CDK’s transformation and delivering long-term value for shareholders, clients and associates well into the future

  <p>I know that CDK Global is the largest global provider of integregated information technology and digital marketing solutions to the automtoive retail industry.
  <p>Knowing that, I was really intrigued by their video in their about me section. Their services handle from the moment buyers step on the lot to notifying owners about service checks, etc.
  <p>'C' Cobalt Digital Marketing
  <p>'D' Dealer Services
  <p>'K' represents Kerridge Computer Company to become a global provider.
skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '5'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: Hyped! Quackcon Project, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Scrabble C++, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Operator Overloading Game, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Tri-Met Ticket App, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Zoom2PDX, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Graph BFS Traversal, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: ACM, folder: 'proj-7', file: 'work/proj-7.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-kia.jpg',
  name: 'Kiarash Torkian',
  title: 'Government Android Developer.',
  quote: '<p><strong>He is asian</strong>, therefore he is smart. Hire him.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-rohan.jpg',
  name: 'Rohan Elukurthy',
  title: 'PSU CS Tutor/Grader.',
  quote: '<p><strong>Larry motivated me to work out and in exchange I tutored him.</strong> I was suprised to see him working on commenting only in his first hackathon to learning bootstrap in his second hackathon.</p>',
  logo: 'logo2.jpg'}
- {avatar: 'face-daniel.jpg',
  name: 'Daniel Eyenis',
  title: 'Viewpoint Intern.',
  quote: '<p><strong>Larry was the chosen one.</strong> When I stepped down as the President of ACM, I had no doubt that this handsome man would step up, and he did.</p>',
  logo: 'logo3.png'}
- {avatar: 'face-nigel.jpg',
  name: 'Nigel Erickson',
  title: 'Larry''s Mentor.',
  quote: '<p><strong>I have watched this man overcomes his faults and strives to better himself.</strong></p>',
  logo: 'logo4.jpg'}


#-------------------------------
# Contact Section

social:
- {icon: 'facebook', link: 'https://www.facebook.com/larry.chiem.3'}
- {icon: 'github', link: 'https://github.com/ChiemyChanga'}
- {icon: 'twitter', link: 'https://twitter.com/ChiemyChonga'}
- {icon: 'youtube', link: 'https://www.youtube.com/user/ChiemyChanga'}
- {icon: 'instagram', link: 'https://instagram.com/ChiemyChanga'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/larrychiem/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
